name: lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev.requirements.txt
    - name: isort checking imports
      run: |
        isort src --check-only --profile black --line-length=120 --nlb=LOCALFOLDER --rr --ca --dt
    - name: black checking format
      run: |
        black src --check
    - name: Analysing the code with pylint
      run: |
        pylint src
        
